# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb17ff107bac10c78e22b7ffc2517c188cc04bbc3f192add71f93755020af9f841886f2eac22f5c3708708f7ed7844074d7ec45cd527a1f0a6efd67cc5891ce4

test:
  secret_key_base: aac2074d83ffdd0ce52cf3df04ad2e9ca3961aec7243d0aacd9a9eb70b5ba99d5875f53f60bd3a5af953ce4c45cf561492e32213b868d83600c3d80461b7383e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
